FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.25.6@sha256:fc24d3881a021e7b968a4610fc024fba749f98fe5c07d4f28e6cfa14dc65a84c AS build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM docker.io/library/alpine:3.23@sha256:865b95f46d98cf867a156fe4a135ad3fe50d2056aa3f25ed31662dff6da4eb62

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="tag-sv"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/tag-sv"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/tag-sv"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/tag-sv"

COPY --from=build /src/dist/tag-sv /bin/tag-sv
CMD ["--help"]
ENTRYPOINT ["/bin/tag-sv"]
