FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.25.0@sha256:4859242e2c392ddc9d3225fd41181c00a443d9cc005b8e5131ce164106fbc676 AS build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM docker.io/library/alpine:3.22@sha256:4bcff63911fcb4448bd4fdacec207030997caf25e9bea4045fa6c8c44de311d1

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="tag-sv"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/tag-sv"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/tag-sv"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/tag-sv"

COPY --from=build /src/dist/tag-sv /bin/tag-sv
CMD ["--help"]
ENTRYPOINT ["/bin/tag-sv"]
